---
- name: Assures .console dir exists in each home directory
  file:
    path: "/home/{{ app_user }}/.console"
    state: directory
    owner: "{{ drupal_console_user }}"
    group: "{{ drupal_console_group }}"

- name: Install drupal console
  composer:
    arguments: "drupal/console:{{ drupal_console_version|d('@stable') }}"
    command: require
    working_dir: /usr/share/composer

- name: Make drupal console available globally
  file:
    src: /usr/share/composer/vendor/bin/drupal
    dest: /usr/bin/drupal
    state: link
    force: no

- name: Enable autocomplete feature system-wide
  template:
    src: console.rc.j2
    dest: /etc/bash_completion.d/drupal
    owner: 'root'
    group: 'root'
    mode: '0644'
